run_first_time=!1;jQuery(document).ready(function($){var loc=window.location.href;loc=loc.split('/');if(loc[loc.length-1].length<2){loc=loc[loc.length-2]}else{loc=loc[loc.length-1]}
$('body').addClass(loc);$(".csutom_footer_ser_link").on('click',function(e){e.preventDefault();$(".csutom_footer_ser_link").removeClass('active show')});$previous_url_history=jQuery.parseJSON(localStorage.getItem('location_history'))||[];if($previous_url_history.length>5)$previous_url_history=$previous_url_history.slice($previous_url_history.length-5,5);if(performance.navigation.type!=1){$previous_url_history.push(window.location.href);localStorage.setItem('location_history',JSON.stringify($previous_url_history))}
if(localStorage.getItem('cookies_yes')!='true'){$('.alert_background_coockies').fadeIn()}
$('#cokkies-submit').click(function(){$('.alert_background_coockies').fadeOut();localStorage.setItem('cookies_yes','true')});$('.display_footer_floating').click(function(){$('.websocialParent').toggleClass('mobile-social-icon')});var owl_for_footer_service=$(".footer_service_name_slide");owl_for_footer_service.owlCarousel({nav:!0,dots:!1,loop:!1,items:7,responsive:{0:{items:2,margin:15},800:{items:3,},1000:{items:5},1200:{items:6}}});var owl=$(".framwork_techstack_slider");owl.owlCarousel({nav:!1,dots:!0,items:5,loop:!1,autoplayHoverPause:!0,itemsDesktop:[1499,4],itemsDesktopSmall:[1199,3],itemsTablet:[899,2],itemsMobile:[599,1],navigation:!1,responsive:{0:{items:2,margin:15},991:{items:4,},600:{items:2},1000:{items:5}}});var owl_trends=$(".saas-trend-carousel");if(owl_trends.length){owl_trends.owlCarousel({nav:!0,items:3,loop:!1,autoplayHoverPause:!0,itemsDesktop:[1499,4],itemsDesktopSmall:[1199,3],itemsTablet:[899,2],itemsMobile:[599,1],navigation:!0,navigationText:['<span class="fa-stack"><i class="fa fa-circle fa-stack-1x"></i><i class="fa fa-chevron-circle-left fa-stack-1x fa-inverse"></i></span>','<span class="fa-stack"><i class="fa fa-circle fa-stack-1x"></i><i class="fa fa-chevron-circle-right fa-stack-1x fa-inverse"></i></span>'],responsive:{0:{items:1,margin:15,nav:!0,dots:!1,},991:{items:4,},600:{items:2,nav:!1,dots:!0,},1000:{items:3,}}})}
$('body').on('click','.mobile-menu-toggler',function(){if($(this).hasClass("on")){$(this).removeClass("on");$(this).find('.icon-bar1').removeClass("header-mobile_menu-custom-top rotate30 rotate45");$(this).find('.icon-bar2').show();$(this).find('.icon-bar3').removeClass("header-mobile_menu-custom-top rotate150 rotate135");$(".mobile-menu-bg").removeClass("expand");$("body").removeClass('mobile_menu')}else{$(this).addClass("on");$(this).find('.icon-bar1').addClass("header-mobile_menu-custom-top rotate30 rotate45");$(this).find('.icon-bar2').hide();$(this).find('.icon-bar3').addClass("header-mobile_menu-custom-top rotate150 rotate135");$(".mobile-menu-bg").addClass("expand");$("body").addClass('mobile_menu')}});$('.mobile-menu-bg').click(function(){$('.mobile-menu-toggler').click()});$('body').on('click','.dropdown-item',function(e){e.stopPropagation();e.preventDefault();$(this).siblings('.dropdown-menu').toggle()});var doAnimations=function(){distanceBottom=50,$window=$(window);$window.scroll(function(){if($window.scrollTop()<distanceBottom){$("nav.header_background").removeClass("show_sticky")}else{$("nav.header_background").addClass("show_sticky")}})};doAnimations();$(window).on('scroll',doAnimations);$(window).trigger('scroll');jQuery("a.nav-link.header_menu").each(function(index){var html='';var path=window.location.href;var current_url=jQuery(this).attr('href');if(path.search(current_url)!=-1){jQuery(this).addClass('text_head');jQuery(this).removeClass('header_menu')}else{jQuery(this).removeClass('text_head')}});jQuery('.get_in_touh').click(function(){jQuery("html, body").animate({scrollTop:$('#contact_footer_form').offset().top-80},600);return!1});var owl=$(".owl-carousel.footer_crousel");owl.owlCarousel({items:3,dots:!0,nav:!0,itemsDesktop:[992,3],itemsDesktopSmall:[768,2],itemsTablet:[480,2],itemsMobile:[320,1],responsive:{0:{items:1,margin:15},600:{items:2,margin:15},1000:{items:3,margin:15}}});$('.tab_content_services').removeClass('tab_force_show');$(window).scroll(function(){$('.all_services').removeClass('mobile-Visible-underline');$('.all_services').each(function(){var distance=$(this).offset().top-160;if($window.scrollTop()>=distance){$(this).addClass('mobile-Visible-underline')}else{$(this).removeClass('mobile-Visible-underline')}})});function isScrolledIntoView(elem){var $elem=$(elem);var $window=$(window);var docViewTop=$window.scrollTop();var docViewBottom=docViewTop+$window.height();var elemTop=$elem.offset().top;var elemBottom=elemTop+$elem.height();return((elemBottom<=docViewBottom)&&(elemTop>=docViewTop))}
var FinalFiles=[];var contactFieldsData={};$('#contactUsForm').on('submit',function(ContSubEvt){ContSubEvt.preventDefault();var stat_error=0;$all_inputs=$(this).find(".required");$all_inputs.each(function(i,v){if(''==v.value){$(this).addClass('required_error');stat_error=1}});var $name=$(this).find("input#user_name").val();var $name_last=($(this).find("input#last_name").length)?$(this).find("input#last_name").val():'';var $company_name=($(this).find("input#company_name").length)?$(this).find("input#company_name").val():'';var timezone_name=$(this).find("select#timezone option:selected").val();var dataValues=($(this).find("select#timezone option:selected").attr('dataValue'));var time=($(this).find("select#starttime option:selected").text());var timeVal=($(this).find("select#starttime option:selected").val());var date=$(this).find("input#date").val();var $vehicle1=($(this).find("input#vehicle1").length)?$(this).find("input#vehicle1").val():'';var $country_code=($('.selected-flag').attr("title"));var $countryId=$country_code.replace(/ \([\s\S]*?\)/g,'');var $contact_no=$(this).find("input#user_phone").val();var $email=$(this).find("input#user_email");var $quotes_=$(this).find("select#quotes_ option:selected").text();var $user_query=$(this).find("#user_query").val();var $attachmentFileField=$(this).find("input#attachmentFile");var india_gmail=0;var $attachmentFile=$attachmentFileField[0].files;var fileTotalSize=0;var _formSubmitBtn=$(".custom_cont_button");if($quotes_=='Schedule Meeting'){if(timezone_name==""){stat_error=1;$($('#contactUsForm #timezone').val()).addClass('required_error');$('.timezone_error').show();$('.timezone_error').html("Please select timezone")}else{$('#contactUsForm #timezone').removeClass('required_error');$('.timezone_error').hide();$('.timezone_error').html("")}
if(date==""){stat_error=1;$(date).addClass('required_error');$('.date_error').show();$('.date_error').html("Please select date")}else{$(date).removeClass('required_error');$('.date_error').hide();$('.date_error').html("")}
if(timeVal==""){stat_error=1;$('#contactUsForm #starttime').addClass('required_error');$('.starttime_error').show();$('.starttime_error').html("Please select timeslot")}else{$('#contactUsForm #starttime').removeClass('required_error');$('.starttime_error').hide();$('.starttime_error').html("")}}else{stat_error=0;$('#contactUsForm #timezone').removeClass('required_error');$('.timezone_error').hide();$('.timezone_error').html("");$(date).removeClass('required_error');$('.date_error').hide();$('.date_error').html("");$('#contactUsForm #starttime').removeClass('required_error');$('.starttime_error').hide();$('.starttime_error').html("")}
if($name==''){stat_error=1;$($name).addClass('required_error');$('.name_error').show();$('.name_error').html("Please enter a name")}else{$($name).removeClass('required_error');$('.name_error').hide();$('.name_error').html("")}
if(validateEmail($email.val())){var $country_code=($('.selected-flag').attr("title"));var $countryvalId=$country_code.replace(/([\s\S]*?: )/g,'');if($countryvalId=="+91"){var em=$email.val();var getDomain=em.substring(em.indexOf('@')+1);if(getDomain=="gmail.com"){india_gmail=1}else{$($email).removeClass('required_error');$('.email_error').hide();$('.email_error').html("")}}else{$($email).removeClass('required_error');$('.email_error').hide();$('.email_error').html("")}}else{stat_error=1;$($email).addClass('required_error');$('.email_error').show();$('.email_error').html("Please enter a valid email")}
if($contact_no!=''){if(!validatePhone($contact_no)){stat_error=1;$('.phone_error').show();$('.phone_error').html("Please enter a valid phone")}else{$('.phone_error').hide();$('.phone_error').html("")}}else{stat_error=1;$('.phone_error').show();$('.phone_error').html("Please enter a phone number")}
if($user_query==''){stat_error=1;$('#user_query').addClass('required_error');$('.query_error').show();$('.query_error').html("Please enter a Comment")}else{$('#user_query').removeClass('required_error');$('.query_error').hide();$('.query_error').html("")}
var recapta=jQuery('#g-recaptcha-response').val().trim();if(recapta==''){jQuery('.error-recap').show();stat_error=1}else{jQuery('.error-recap').hide()}
var _validFileExtensions=[".jpg",".jpeg",".bmp",".gif",".png",".doc",".pdf"];var allowedExtensions=/(\.jpg|\.jpeg|\.png|\.gif|\.doc|\.pdf|\.bmp)$/i;var file_extension_error=!1;if(FinalFiles.length>5){stat_error=1;$(".file_error").show();$(".file_max_size_error").text('Max 5 files are allowed.')}else if(FinalFiles.length!=0){$(".file_max_size_error").text('');$.each(FinalFiles,function(i,v){if(allowedExtensions.exec(v.name)){}else{stat_error=1;file_extension_error=!0}
fileTotalSize+=v.size});if(file_extension_error){$(".not-allow").text('Only images, doc and pdf files are allowed.');$(".file_error").show()}else{$(".not-allow").text('');$(".file_error").hide()}
if(fileTotalSize>25000000){stat_error=1;$(".file_error").show();$(".file_total_limit_error").text('Your files exceed the max size of 25 MB.')}else{$(".file_total_limit_error").text('')}}
var time=($(this).find("select#starttime option:selected").text());var $date=$(this).find("input#date").val();contactFieldsData={'user_name':$name+' '+$name_last,'country_code':$countryId,'user_phone':$contact_no,'user_email':$email.val(),'quotes_':$quotes_,'user_query':$user_query,'company_name':$company_name,'vehicle1':$vehicle1,'india_gmail':india_gmail,'timezone':dataValues+' '+timezone_name,'time':time,'date':date,'time_val':timeVal};if($('.input_career_mail').length){var career_mail=$('.input_career_mail').attr('value')}else{var career_mail=0}
if(stat_error==1){return!1}else{filesObject=new FormData();filesObject.append('fields',JSON.stringify(contactFieldsData));filesObject.append('previous_url',document.referrer);filesObject.append('current_url',window.location.href);filesObject.append('all_history',localStorage.getItem('location_history'));filesObject.append('g-recaptcha-response',recapta);filesObject.append('action','custom_conatct_us_submit');filesObject.append('career_mail',career_mail);$.each(FinalFiles,function(i,v){filesObject.append(i,v)})}
$.ajax({url:customObject.ajaxurl,type:'POST',data:filesObject,processData:!1,beforeSend:function(){_formSubmitBtn.attr("disabled","disabled");_formSubmitBtn.append('<i class="fa fa-spinner fa-spin" style="font-size:24px"></i>')},contentType:!1,success:function(res){var should_return=!1;if(res.errors!=''){$.each(res.errors,function(i,v){$("#"+i).addClass('required_error');should_return=!0})}
if(res.files_error.file_count){$(".file_max_size_error").text('Max 5 files are allowed.');should_return=!0}
if(res.files_error.file_size){$(".file_total_limit_error").text('Your files exceed the max size of 25 MB.');should_return=!0}
if(res.files_error.file_extension_error){$(".not-allow").text('Only images, doc and pdf files are allowed.');$(".file_error").show();should_return=!0}else{$(".not-allow").text('')}
if(should_return){return}else{if(res.mail_status){var rand_number=create_cookie();window.location.href=customObject.home_url+'/thankyou?id='+rand_number}else{}}},error:function(xhr){},complete:function(){_formSubmitBtn.removeAttr("disabled","disabled");_formSubmitBtn.find('i').remove();$("body #contactUsForm")[0].reset();FinalFiles=[];$(".files_list").html("");$("#attchment_text").text('Attach files')}});return!1});$('#contactUsFormDev').on('submit',function(ContSubEvt){ContSubEvt.preventDefault();var stat_error=0;$all_inputs=$(this).find(".required");$all_inputs.each(function(i,v){if(''==v.value){$(this).addClass('required_error');stat_error=1}});var $name=$(this).find("input#user_name").val();var $name_last=($(this).find("input#last_name").length)?$(this).find("input#last_name").val():'';var $company_name=($(this).find("input#company_name").length)?$(this).find("input#company_name").val():'';var india_gmail=0;var $vehicle1=($(this).find("input#vehicle1").length)?$(this).find("input#vehicle1").val():'';var $country_code=($('.selected-flag').attr("title"));var $countryId=$country_code.replace(/ \([\s\S]*?\)/g,'');var $contact_no=$(this).find("input#user_phone_dev").val();var $email=$(this).find("input#user_email");var $quotes_=$(this).find("select#quotes_ option:selected").text();var $user_query=$(this).find("#user_query_dev").val();var _formSubmitBtn=$(".custom_cont_button");if($name==''){stat_error=1;$($name).addClass('required_error');$('.name_error_dev').show();$('.name_error_dev').html("Please enter a name")}else{$($name).removeClass('required_error');$('.name_error_dev').hide();$('.name_error_dev').html("")}
if(validateEmail($email.val())){var $country_code=($('.selected-flag').attr("title"));var $countryvalId=$country_code.replace(/([\s\S]*?: )/g,'');if($countryvalId=="+91"){var em=$email.val();var getDomain=em.substring(em.indexOf('@')+1);if(getDomain=="gmail.com"){india_gmail=1}else{$($email).removeClass('required_error');$('.email_error_dev').hide();$('.email_error_dev').html("")}}else{$($email).removeClass('required_error');$('.email_error_dev').hide();$('.email_error_dev').html("")}}else{stat_error=1;$($email).addClass('required_error');$('.email_error_dev').show();$('.email_error_dev').html("Please enter a valid email")}
if($contact_no!=''){if(!validatePhone($contact_no)){stat_error=1;$('.phone_error_dev').show();$('.phone_error_dev').html("Please enter a valid phone")}else{$('.phone_error_dev').hide();$('.phone_error_dev').html("")}}else{stat_error=1;$('.phone_error_dev').show();$('.phone_error_dev').html("Please enter a phone number")}
if($user_query==''){stat_error=1;$('#user_query_dev').addClass('required_error');$('.query_error_dev').show();$('.query_error_dev').html("Please enter a Comment")}else{$('#user_query_dev').removeClass('required_error');$('.query_error_dev').hide();$('.query_error_dev').html("")}
contactFieldsData={'user_name':$name+' '+$name_last,'country_code':$countryId,'user_phone':$contact_no,'user_email':$email.val(),'quotes_':$quotes_,'user_query':$user_query,'company_name':$company_name,'vehicle1':$vehicle1,'india_gmail':india_gmail};if($('.input_career_mail').length){var career_mail=$('.input_career_mail').attr('value')}else{var career_mail=0}
if(stat_error==1){return!1}else{filesObject=new FormData();filesObject.append('fields',JSON.stringify(contactFieldsData));filesObject.append('previous_url',document.referrer);filesObject.append('current_url',window.location.href);filesObject.append('all_history',localStorage.getItem('location_history'));filesObject.append('g-recaptcha-response',!1);filesObject.append('action','custom_conatct_us_submit');filesObject.append('career_mail',career_mail)}
$.ajax({url:customObject.ajaxurl,type:'POST',data:filesObject,processData:!1,beforeSend:function(){_formSubmitBtn.attr("disabled","disabled");_formSubmitBtn.append('<i class="fa fa-spinner fa-spin" style="font-size:24px"></i>')},contentType:!1,success:function(res){var should_return=!1;if(res.errors!=''){$.each(res.errors,function(i,v){$("#"+i).addClass('required_error');should_return=!0})}
if(res.files_error.file_count){$(".file_max_size_error").text('Max 5 files are allowed.');should_return=!0}
if(res.files_error.file_size){$(".file_total_limit_error").text('Your files exceed the max size of 25 MB.');should_return=!0}
if(res.files_error.file_extension_error){$(".not-allow").text('Only images, doc and pdf files are allowed.');$(".file_error").show();should_return=!0}else{$(".not-allow").text('')}
if(should_return){return}else{if(res.mail_status){var rand_number=create_cookie();window.location.href=customObject.home_url+'/thankyou?id='+rand_number}else{}}},error:function(xhr){},complete:function(){_formSubmitBtn.removeAttr("disabled","disabled");_formSubmitBtn.find('i').remove();$("body #contactUsFormDev")[0].reset()}});return!1});$("#quotes_").on("change",function(){var value_quote=$(this).find('option:selected').attr('value');var user_query_container=$("#user_query_dev");if(value_quote=='General Query'){user_query_container.attr('placeholder','How can we help')}else if(value_quote=='Request for Proposal'){user_query_container.attr('placeholder','Tell us about your project')}});$("#quotes_1").on("change",function(){var value_quote=$(this).find('option:selected').attr('value');var user_query_container=$("#usercomment1");if(value_quote=='General Query'){user_query_container.attr('placeholder','How can we help')}else if(value_quote=='Request a proposal'){user_query_container.attr('placeholder','Tell us about your project')}});$(".key_up_remove_error").on('keyup',function(){$(this).removeClass('required_error');if(''==$(this).val()){$(this).addClass('required_error')}else{if('email'==$(this).attr('type')){if(validateEmail($(this).val())){$(".email_error_dev").text('')}}}
if($(this).attr('id')=='user_phone_dev'){var phone_value=$(this).val().replace(/[^+\d]/g,'');$(this).val(phone_value)}});$("#user_phone_dev").on("keyup",function(){var phone_value=$(this).val().replace(/[^+\d]/g,'');$(this).val(phone_value)});$("input#attachmentFile").on('change',function(fileEv){var fileTotalSize=0;$(".file_error").hide();var ii=FinalFiles.length;$.each(fileEv.target.files,function(i,v){$(".appended_files").find("span."+v.name.replace(/[^A-Z0-9]/ig,"_")).parent().remove();fileTotalSize+=v.size;index_id=(i+ii);FinalFiles[i+ii]=v;if(v.name.length>11){var fl_name=v.name.substring(0,11)+'...'}else{var fl_name=v.name}
$(".files_list").append("<div class='appended_files'><span class='"+v.name.replace(/[^A-Z0-9]/ig,"_")+"'>"+fl_name+" <a href='javascript:void(0)' class='custom_contact_file_remove' data-attr-id='"+index_id+"' ><i class='fa fa-times attch_cross_icon' aria-hidden='true'></i></a></span></div>")});console.log('ssdsds');if(FinalFiles.length>5){$(".file_error").show();$(".file_max_size_error").text('Max 5 files are allowed.')}else{$(".file_max_size_error").text('')}
if(FinalFiles.length>0){$("#attchment_text").text('')}
if(fileTotalSize>25000000){$(".file_error").show();$(".file_total_limit_error").text('Your files exceed the max size of 25 MB.')}else{$(".file_total_limit_error").text('')}});function validateEmail(email){var re=/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;return re.test(email)}
function validatePhone(phone){var validity=new RegExp("^[0-9\+]{6,17}$");return validity.test(phone)}
$(".open_uploader").on("click",function(){$('#attachmentFile').trigger('click')});jQuery("body").on("click",'.custom_contact_file_remove',function(){var input=$('input#attachmentFile');var dataAttrId=$(this).attr('data-attr-id');var fsize=0;$(this).parents(".appended_files").remove();$(".appended_files").each(function(i,v){$(this).find('.custom_contact_file_remove').attr("data-attr-id",i)});delete FinalFiles[dataAttrId];FinalFiles=FinalFiles.filter(function(el){return el!=null});if(FinalFiles.length<1){$("#attchment_text").text('Attach files');input.replaceWith(input.val('').clone(!0))}
if(FinalFiles.length<5||FinalFiles.length==5){$(".file_max_size_error").text('')}
$.each(FinalFiles,function(i,v){fsize+=v.size});if(fsize<25000000){$(".file_total_limit_error").text('')}});jQuery('.button_for_icons').on('click',function(){if($(this).hasClass('close_icons')){$(this).removeClass('close_icons')}else{$(this).addClass('close_icons')}});jQuery('.scroll-to-top span').click(function(){jQuery("html, body").animate({scrollTop:0},600);return!1});jQuery(window).scroll(function(){if(jQuery(this).scrollTop()>300){jQuery('.scroll-to-top span').fadeIn()}else{jQuery('.scroll-to-top span').fadeOut()}
var sticky=jQuery('#header'),scroll=jQuery(window).scrollTop();if(scroll>=300)sticky.addClass('fixed');else sticky.removeClass('fixed')});jQuery('#msgs1').hide();jQuery("#info").click(function(){jQuery('#info_form').fadeIn();if(!run_first_time){if(!jQuery("#re_captcha_custom").length){var po=document.createElement('script');po.type='text/javascript';po.async=!0;po.defer=!0;po.id='re_captcha_custom';po.src='https://www.google.com/recaptcha/api.js';var elem=document.querySelector('script[nonce]');var n=elem&&(elem.nonce||elem.getAttribute('nonce'));if(n){po.setAttribute('nonce',n)}
var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(po,s)}}});jQuery(".cross").click(function(){jQuery('#username1').css('border-color','');jQuery('#emailid1').css('border-color','');jQuery('#usercomment1').css('border-color','');jQuery('.user-name-error').hide();jQuery('.email-error').hide();jQuery('.user-comment-error').hide();jQuery('.error-msg').hide();jQuery("#emailid1").removeClass("required_error");document.getElementById("contactForm").reset();jQuery('#info_form').fadeOut()});$(".name-require").hide();$(".email-require").hide();$(".email-error").hide();$(".comment-require").hide();function check_recaptcha(){var recp_val=jQuery('#g-recaptcha-response-1').val().trim();if(recp_val==''){jQuery('.error-recap-1').show();return recp_val}else{jQuery('.error-recap-1').hide();return recp_val}}
function create_cookie(){var max=999999999,min=11111;var rand_num=Math.random()*(+max- +min)+ +min;previous_contact_submit=jQuery.parseJSON(localStorage.getItem('contact_submit_history'))||[];previous_contact_submit.push(rand_num);var itemforcache=localStorage.setItem('contact_submit_history',JSON.stringify(previous_contact_submit));var now=new Date();var time=now.getTime();time+=3600*1000;now.setTime(time);document.cookie='access_thankyou='+previous_contact_submit+'; path=/';return rand_num}
$(document).ready(function(){var d=new Date();var n=d.toTimeString();var nn=n.split(" ")[1];var ret=nn.replace('GMT','');var str=ret;var chr=':'
var pos=3;strNew=str.substring(0,pos)+chr+str.substring(pos,str.length);var currentTimezone=Intl.DateTimeFormat().resolvedOptions().timeZone;console.log(currentTimezone);$("#timezone option[dataValue='"+currentTimezone+"'  ]").prop("selected",!0);$.ajax({url:"/timezonenew.php",method:"POST",data:{DefTimezone:strNew,DataValues:currentTimezone},success:function(data){$('#starttime').html(data)}});$('#timezone').change(function(){var timezone_name=$(this).val();var dataValues=($(this).find("option:selected").attr('dataValue'));$.ajax({url:"/timezone.php",method:"POST",data:{timezone_Name:timezone_name,DataValues:dataValues},success:function(data){$('#starttime').html(data)}})})
$("#timezone").change(function(){$("#starttime").prop('disabled',!0);$('#date').val(new Date())});$("#starttime").prop('disabled',!0);$("#date").click(function(){$("#starttime").prop('disabled',!1)});$('#date').on('change',function(){var currentdate=new Date().toISOString().slice(0,10);var selectedDate=$("#date").val();if(currentdate===selectedDate){var now=new Date();var valueDate=now.toLocaleDateString("en-US",{timeZone:dataValues});var dataValues=($('#timezone').find("option:selected").attr('dataValue'));var value=now.toLocaleTimeString("en-US",{timeZone:dataValues,hour:'2-digit',minute:'2-digit',hour12:!1});console.log(valueDate+' '+value);$('#starttime').find('option').prop('disabled',!1);$('#starttime').find('option').each(function(i,e){var opt=$(e);if(Date.parse(selectedDate+' '+opt.val())<Date.parse(valueDate+' '+value)){console.log(selectedDate+' '+opt.val());opt.prop('disabled',!0)}});$("#starttime").val("")}else{var now=new Date();var valueDate=now.toLocaleDateString();var value=now.toLocaleTimeString();$('#starttime').find('option').prop('disabled',!1);$('#starttime').find('option').each(function(i,e){var opt=$(e);if(opt.val()<value){opt.prop('disabled',!1)}})}});var today=new Date();var dd=today.getDate();var mm=today.getMonth()+1;var yyyy=today.getFullYear();if(dd<10){dd='0'+dd}
if(mm<10){mm='0'+mm}
today=yyyy+'-'+mm+'-'+dd;document.getElementById("date").setAttribute("min",today)});$(document).ready(function(){$('#quotes_').change(function(){var $option=$(this).find('option:selected');var value=$option.val();if(value=="schedule_meetings"){$('#timezone-row-1').css("display","block");$('#timezone-row-2').css("display","block");$('#timezone-row-3').css("display","block")}
if(value=="Request for Proposal"||value=="request_a_proposal"){$('select#starttime option:selected').attr("selected",!1);$('#timezone-row-1').css("display","none");$('#timezone-row-2').css("display","none");$('#timezone-row-3').css("display","none")}
if(value=="General Query"||value=='general_query'){$('select#starttime option:selected').attr("selected",!1);$('#timezone-row-1').css("display","none");$('#timezone-row-2').css("display","none");$('#timezone-row-3').css("display","none")}})});jQuery("#contactForm").submit(function(e){e.preventDefault();var checked_userName=check_name();var checked_userEmail=check_email();var checked_userComment=check_comment();var recapta=check_recaptcha();var india_gmail=0;var err=0;var countryCode=getCookie('country_code');if(countryCode=="IN"){var emailid1=$('#emailid1').val();var getDomain=emailid1.substring(emailid1.indexOf('@')+1);if(getDomain=="gmail.com"){india_gmail=1}}
jQuery('#msgs1').hide();if(checked_userName&&checked_userComment&&checked_userEmail&&recapta&&err==0){var namevalue=jQuery('#username1').val();var emailvalue=jQuery('#emailid1').val();var userQuote=jQuery('#quotes_1').val();var commentvalue=jQuery('#usercomment1').val();jQuery('#submit_info').hide();jQuery('#msgs1').show();jQuery.ajax({type:"POST",url:customObject.ajaxurl,data:{'action':'send_proposel_request','name':namevalue,'email':emailvalue,'quote':userQuote,'message':commentvalue,'india_gmail':india_gmail,'previous_url':$('.previous_url').val(),'current_url':$('.current_url').val(),'g-recaptcha-response':recapta},success:function(data){jQuery('#submit_info').show();jQuery('#msgs1').hide();document.getElementById("contactForm").reset();if(data){var rand_number=create_cookie();window.location.href=customObject.home_url+'/thankyou?id='+rand_number;jQuery('#info').hide();jQuery('#info_form').fadeOut()}else{}},complete:function(){}})}});jQuery("#contactFormApp").submit(function(e){e.preventDefault();var checked_userName=check_name();var checked_userEmail=check_email();var checked_userComment=check_comment();jQuery('#msgs1').hide();if(checked_userName&&checked_userComment&&checked_userEmail){var namevalue=jQuery('#username1').val();var emailvalue=jQuery('#emailid1').val();var userQuote=jQuery('#quotes_1').val();var commentvalue=jQuery('#usercomment1').val();jQuery('#submit_info').hide();jQuery('#msgs1').show();jQuery.ajax({type:"POST",url:customObject.ajaxurl,data:{'action':'send_proposel_request','name':namevalue,'email':emailvalue,'quote':userQuote,'message':commentvalue,'previous_url':$('.previous_url').val(),'current_url':$('.current_url').val(),'g-recaptcha-response':!1},success:function(data){jQuery('#submit_info').show();jQuery('#msgs1').hide();document.getElementById("contactForm").reset();if(data){var rand_number=create_cookie();window.location.href=customObject.home_url+'/thankyou?id='+rand_number;jQuery('#info').hide();jQuery('#info_form').fadeOut()}else{}},complete:function(){}})}});function check_name(){var userNameValue=jQuery('#username1').val().trim();if(jQuery('#username1').val().trim()==''){jQuery('#username1').css('border-color','#d40f2a');jQuery(".user-name-error").hide();jQuery(".name-require").show();return!1}else{$(".name-require").hide();jQuery('#username1').css('border-color','');return!0}}
function check_email(){var email=jQuery("#emailid1").val().trim();if(jQuery('#emailid1').val().trim()==''){$(".email-require").show();$(".email-error").hide();jQuery('#emailid1').css('border-color','#d40f2a');return!1}else{$(".email-require").hide();jQuery('#emailid1').css('border-color','');if(isValidEmail1(email)){jQuery('#emailid1').css('border-color','');jQuery('.email-error').hide();return!0}else{jQuery('#emailid1').css('border-color','#d40f2a');jQuery('.email-error').show();return!1}}}
function check_comment(){var customCommentValue=jQuery('#usercomment1').val().trim();if(jQuery('#usercomment1').val().trim()==''){$(".comment-require").show();jQuery('#usercomment1').css('border-color','#d40f2a');return!1}else{$(".comment-require").hide();jQuery('#usercomment1').css('border-color','');return!0}}
function isValidEmail1(emailAddress){var pattern=/^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/;return pattern.test(emailAddress)}
$('.container_trends').each(function(){if($(this).find('.custom_trends').text().length==0){$(this).remove()}})});jQuery(window).scroll(function(){if(jQuery('#contact_footer_form').length){var hT=jQuery('#contact_footer_form').offset().top,hH=jQuery('#contact_footer_form').outerHeight(),wH=jQuery(window).height(),wS=jQuery(this).scrollTop();if(wS>(hT-wH+20)){jQuery('#info').fadeOut(300)}else{jQuery('#info').fadeIn(300)}}
if(jQuery('.custom_captcha').length){if(!run_first_time){var pageTop=jQuery(window).scrollTop();var pageBottom=pageTop+jQuery(window).height();var elementTop=jQuery('.custom_captcha').offset().top;var elementBottom=elementTop+jQuery('.custom_captcha').height();if(((elementTop<=pageBottom)&&(elementBottom>=pageTop))){run_first_time=!0;if(!jQuery("#re_captcha_custom").length){var po=document.createElement('script');po.type='text/javascript';po.async=!0;po.defer=!0;po.src='https://www.google.com/recaptcha/api.js';var elem=document.querySelector('script[nonce]');var n=elem&&(elem.nonce||elem.getAttribute('nonce'));if(n){po.setAttribute('nonce',n)}
var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(po,s)}}else{}}}});$('.discover_carousel').owlCarousel({loop:!1,margin:10,dots:!0,nav:!1,responsive:{0:{items:1},700:{items:2},1150:{items:3}}})
$('.erp-i40-slider-item-1').owlCarousel({loop:!0,margin:10,nav:!0,navText:[`<div class='prev-slide'>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="16.889" viewBox="0 0 24 16.889">
        <path d="M0 8.439a1.11 1.11 0 0 1 .222-.583L6.889.3a.886.886 0 0 1 1.333 1.167L2.847 7.55h20.264a.889.889 0 0 1 0 1.778H2.847l5.375 6.083a.861.861 0 0 1-.116 1.248.834.834 0 0 1-1.218-.081L.221 9.023A.873.873 0 0 1 0 8.439z" data-name="Path 35"/>
      </svg>  
    </div>`,`<div class='next-slide'>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="16.889" viewBox="0 0 24 16.889">
        <path d="M24 8.444a1.11 1.11 0 0 0-.222-.583L17.111.305a.886.886 0 0 0-1.333 1.167l5.375 6.083H.889a.889.889 0 0 0 0 1.778h20.264l-5.375 6.083a.861.861 0 0 0 .116 1.248.834.834 0 0 0 1.218-.081l6.667-7.556a.873.873 0 0 0 .222-.583z" data-name="Path 35"/>
      </svg>
    </div>`],responsive:{0:{items:1}}})
$('.erp-i40-slider-cards').owlCarousel({loop:!1,margin:0,nav:!0,dots:!1,navText:[`<div class='prev-slide'>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="16.889" viewBox="0 0 24 16.889">
        <path d="M0 8.439a1.11 1.11 0 0 1 .222-.583L6.889.3a.886.886 0 0 1 1.333 1.167L2.847 7.55h20.264a.889.889 0 0 1 0 1.778H2.847l5.375 6.083a.861.861 0 0 1-.116 1.248.834.834 0 0 1-1.218-.081L.221 9.023A.873.873 0 0 1 0 8.439z" data-name="Path 35"/>
      </svg>  
    </div>`,`<div class='next-slide'>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="16.889" viewBox="0 0 24 16.889">
        <path d="M24 8.444a1.11 1.11 0 0 0-.222-.583L17.111.305a.886.886 0 0 0-1.333 1.167l5.375 6.083H.889a.889.889 0 0 0 0 1.778h20.264l-5.375 6.083a.861.861 0 0 0 .116 1.248.834.834 0 0 0 1.218-.081l6.667-7.556a.873.873 0 0 0 .222-.583z" data-name="Path 35"/>
      </svg>
    </div>`],responsive:{0:{items:1,nav:!1,dots:!0},600:{items:2},1000:{items:4}}})
$('.erpi40-blogs_slider').owlCarousel({loop:!1,margin:30,nav:!0,dots:!1,navText:[`<div class='prev-slide'>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="16.889" viewBox="0 0 24 16.889">
        <path d="M0 8.439a1.11 1.11 0 0 1 .222-.583L6.889.3a.886.886 0 0 1 1.333 1.167L2.847 7.55h20.264a.889.889 0 0 1 0 1.778H2.847l5.375 6.083a.861.861 0 0 1-.116 1.248.834.834 0 0 1-1.218-.081L.221 9.023A.873.873 0 0 1 0 8.439z" data-name="Path 35"/>
      </svg>  
    </div>`,`<div class='next-slide'>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="16.889" viewBox="0 0 24 16.889">
        <path d="M24 8.444a1.11 1.11 0 0 0-.222-.583L17.111.305a.886.886 0 0 0-1.333 1.167l5.375 6.083H.889a.889.889 0 0 0 0 1.778h20.264l-5.375 6.083a.861.861 0 0 0 .116 1.248.834.834 0 0 0 1.218-.081l6.667-7.556a.873.873 0 0 0 .222-.583z" data-name="Path 35"/>
      </svg>
    </div>`],responsive:{0:{items:1,nav:!1,dots:!0},600:{items:2,},1000:{items:4,}}})
function openCity(evt,cityName){let i,tabcontent,tablinks;tabcontent=document.getElementsByClassName("tabcontent");for(i=0;i<tabcontent.length;i++){tabcontent[i].style.display="none"}
tablinks=document.getElementsByClassName("tablinks");for(i=0;i<tablinks.length;i++){tablinks[i].className=tablinks[i].className.replace(" active","")}
document.getElementById(cityName).style.display="block";evt.currentTarget.className+=" active"}
function openevent(evt,cityName){let i,tabcontent,tablinks;tabcontent=document.getElementsByClassName("tabcontents");for(i=0;i<tabcontent.length;i++){tabcontent[i].style.display="none"}
tablinks=document.getElementsByClassName("tablink");for(i=0;i<tablinks.length;i++){tablinks[i].className=tablinks[i].className.replace(" active","")}
document.getElementById(cityName).style.display="block";evt.currentTarget.className+=" active"}
$(document).ready(function(){$('.main_erp_form_input').change(function(){if($(this).val()!=""){$(this).siblings('.input-name').addClass('ierp_input_focus')}else{$(this).siblings('.input-name').removeClass('ierp_input_focus')}});$('.tabcontent').css('display','none');$('.tabcontents').css('display','none');$('#default_Open').addClass('active');$('#defaultOpen1').addClass('active');$('#horizontal_tabs_1').css('display','block');$('#vertical_tabs_1').css('display','block')});$(document).on('click','.casestudy_link',function(){$('#casestudy_url').val($(this).data('attr'));$('#modalRegister').modal('show')});$(document).on('click','.cl_modal',function(){$('#casestudyForm')[0].reset()});$(document).ready(function(){jQuery("#casestudyForm").submit(function(e){e.preventDefault();var firstname=jQuery('#firstname').val();var emailvalue=jQuery('#emailid').val();var lastname=jQuery('#lastname').val();var company=jQuery('#company').val();var casestudy_url=$('#casestudy_url').val();console.log(firstname+" "+lastname+" "+emailvalue+" "+company);jQuery.ajax({type:"POST",url:customObject.ajaxurl,data:{'action':'store_casestudy_visitor_data','firstname':firstname,'email':emailvalue,'lastname':lastname,'company':company,'previous_url':$('.previous_url').val(),'current_url':$('.current_url').val(),},success:function(data){if(data){$('#casestudyForm')[0].reset();$('#modalRegister').modal('hide');window.open(casestudy_url,"_blank")}else{alert(data)}},complete:function(){}})})})