(function($){var my_subscription=function(){if(!(this instanceof my_subscription)){return new my_subscription()}};my_subscription.fn=my_subscription.prototype={init:function(){sub_this_prototype=this;sub_this_prototype.register_events_functions()},register_events_functions:function(){$(".subscribe_btn").on('click',function(){var filter=/^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/,sEmail=$(".subscribe_input").val();if(sEmail!=''){if(filter.test(sEmail)){$(".subscribe_required_error").text('');$(".subscribe_input").removeClass('subscrib_email_error');sub_this_prototype.send_ajax(sEmail)}else{$(".subscribe_required_error").text('Invalid email.');$(".subscribe_input").addClass('subscrib_email_error')}}else{$(".subscribe_required_error").text('Email is required.')}})},send_ajax:function(email){_formSubmitBtn=$(".subscribe_btn");$.ajax({url:customObj.ajaxurl,type:'POST',data:{'action':'get_subscription_request','email':email},beforeSend:function(){_formSubmitBtn.attr("disabled","disabled");_formSubmitBtn.append('<i class="fa fa-spinner fa-spin" style="font-size:24px"></i>')},success:function(res){_formSubmitBtn.attr("disabled",!1);_formSubmitBtn.find(".fa-spinner").remove();$(".subscribe_input").val('');if(res.success){$("#subscriptionModalCenter").modal('toggle')}else{$(".subscribe_required_error").text('Invalid email.');$(".subscribe_input").addClass('subscrib_email_error')}},error:function(xhr){_formSubmitBtn.attr("disabled",!1);_formSubmitBtn.find(".fa-spinner").remove();$(".subscribe_required_error").text('Please try again.');$(".subscribe_input").addClass('subscrib_email_error')},complete:function(){_formSubmitBtn.removeAttr("disabled","disabled");_formSubmitBtn.find('i').remove()}})}};window.my_subscription=my_subscription;my_subscription.fn.init()})(jQuery);document.addEventListener("DOMContentLoaded",function(){var lazyloadImages=document.querySelectorAll("[data-src]");var lazyloadThrottleTimeout;function lazyload(){if(lazyloadThrottleTimeout){clearTimeout(lazyloadThrottleTimeout)}
lazyloadThrottleTimeout=setTimeout(function(){var scrollTop=window.pageYOffset;lazyloadImages.forEach(function(img){if(img.offsetTop<(window.innerHeight+scrollTop)){img.src=img.dataset.src;img.classList.remove('lazy')}});if(lazyloadImages.length==0){document.removeEventListener("scroll",lazyload);window.removeEventListener("resize",lazyload);window.removeEventListener("orientationChange",lazyload)}},20)}
document.addEventListener("scroll",lazyload);window.addEventListener("resize",lazyload);window.addEventListener("orientationChange",lazyload);window.scrollTo(0,1)});document.addEventListener("DOMContentLoaded",function(){var lazyloadImages;if("IntersectionObserver" in window){lazyloadImages=document.querySelectorAll(".lazy");var imageObserver=new IntersectionObserver(function(entries,observer){entries.forEach(function(entry){if(entry.isIntersecting){var image=entry.target;image.classList.remove("lazy");imageObserver.unobserve(image)}})});lazyloadImages.forEach(function(image){imageObserver.observe(image)})}else{var lazyloadThrottleTimeout;lazyloadImages=document.querySelectorAll(".lazy");function lazyload(){if(lazyloadThrottleTimeout){clearTimeout(lazyloadThrottleTimeout)}
lazyloadThrottleTimeout=setTimeout(function(){var scrollTop=window.pageYOffset;lazyloadImages.forEach(function(img){if(img.offsetTop<(window.innerHeight+scrollTop)){img.src=img.dataset.src;img.classList.remove('lazy')}});if(lazyloadImages.length==0){document.removeEventListener("scroll",lazyload);window.removeEventListener("resize",lazyload);window.removeEventListener("orientationChange",lazyload)}},20)}
document.addEventListener("scroll",lazyload);window.addEventListener("resize",lazyload);window.addEventListener("orientationChange",lazyload)}})
$(document).ready(function(){$(".hd1 a.nav-link.header_menu.bknd").hover(function(){$('.backend').css("border-bottom",'4px solid #2F83C5')},function(){$('.backend').css("border-bottom",'none')});$(".hd1 a.nav-link.header_menu.frntnd").hover(function(){$('.frontend').css("border-bottom",'4px solid #2F83C5')},function(){$('.frontend').css("border-bottom",'none')});$(".hd1 a.nav-link.header_menu.fs").hover(function(){$('.fullstack').css("border-bottom",'4px solid #2F83C5')},function(){$('.fullstack').css("border-bottom",'none')});$(".hd1 a.nav-link.header_menu.bs").hover(function(){$('.blockchain').css("border-bottom",'4px solid #2F83C5')},function(){$('.blockchain').css("border-bottom",'none')});$(".hd1 a.nav-link.header_menu.mb").hover(function(){$('.mobile').css("border-bottom",'4px solid #2F83C5')},function(){$('.mobile').css("border-bottom",'none')});$(".hd1 a.nav-link.header_menu.ep").hover(function(){$('.erp').css("border-bottom",'4px solid #2F83C5')},function(){$('.erp').css("border-bottom",'none')});$(".hd1 a.nav-link.header_menu.ec").hover(function(){$('.e-com').css("border-bottom",'4px solid #2F83C5')},function(){$('.e-com').css("border-bottom",'none')});$(".hd1 a.nav-link.header_menu.vs").hover(function(){$('.video').css("border-bottom",'4px solid #2F83C5')},function(){$('.video').css("border-bottom",'none')});$(".hd1 a.nav-link.header_menu.cs").hover(function(){$('.cms').css("border-bottom",'4px solid #2F83C5')},function(){$('.cms').css("border-bottom",'none')});$(".hd1 a.nav-link.header_menu.dv").hover(function(){$('.devops').css("border-bottom",'4px solid #2F83C5')},function(){$('.devops').css("border-bottom",'none')});$(".hd1 a.nav-link.header_menu.av").hover(function(){$('.ar-vr').css("border-bottom",'4px solid #2F83C5')},function(){$('.ar-vr').css("border-bottom",'none')})});function mySkillnavcustommobile(){var x=document.getElementById("mySKILLDIVnavmobile");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function mySkillSUBcustommobile(){var x=document.getElementById("mySKILLnavmobile");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function mySkillSUBcustommobile1(){var x=document.getElementById("mySKILLnavmobile1");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function mySkillSUBcustommobile2(){var x=document.getElementById("mySKILLnavmobile2");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function mySkillSUBcustommobile3(){var x=document.getElementById("mySKILLnavmobile3");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function mySkillSUBcustommobile4(){var x=document.getElementById("mySKILLnavmobile4");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function mySkillSUBcustommobile5(){var x=document.getElementById("mySKILLnavmobile5");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function mySkillSUBcustommobile6(){var x=document.getElementById("mySKILLnavmobile6");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function mySkillSUBcustommobile7(){var x=document.getElementById("mySKILLnavmobile7");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function mySkillSUBcustommobile8(){var x=document.getElementById("mySKILLnavmobile8");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function mySkillSUBcustommobile9(){var x=document.getElementById("mySKILLnavmobile9");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function mySkillSUBcustommobile10(){var x=document.getElementById("mySKILLnavmobile10");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function mySkillSUBcustommobile11(){var x=document.getElementById("mySKILLnavmobile11");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function mySkillSUBcustommobile12(){var x=document.getElementById("mySKILLnavmobile12");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function mySkillSUBcustommobile13(){var x=document.getElementById("mySKILLnavmobile13");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function mySkillSUBcustommobile14(){var x=document.getElementById("mySKILLnavmobile14");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function myFunctionnavcustommobile(){var x=document.getElementById("myDIVnavmobile");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function myFunctionnavcustommobile(){var x=document.getElementById("myDIVnavmobile");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function myFunctionnavcustommobilesolution(){var x=document.getElementById("myDIVnavmobilesolution");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function myFunctionSUBcustommobilesolution(){var x=document.getElementById("mySUBnavmobilesolution");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function myFunctionnavcustommobilecompany(){var x=document.getElementById("myDIVnavmobilecompany");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function myFunctionSUBcustommobilecompany(){var x=document.getElementById("mySUBnavmobilecompany");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function myFunctionSUBcustommobile(){var x=document.getElementById("mySUBnavmobile");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function myFunctionSUBcustommobile1(){var x=document.getElementById("mySUBnavmobile1");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function myFunctionSUBcustommobile2(){var x=document.getElementById("mySUBnavmobile2");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function myFunctionSUBcustommobile3(){var x=document.getElementById("mySUBnavmobile3");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}
function myFunctionSUBcustommobile4(){var x=document.getElementById("mySUBnavmobile4");if(x.style.display==="none"){x.style.display="block"}else{x.style.display="none"}}